//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public string offer_name { get; set; }
        public string offer_description { get; set; }
        public int room_type_id { get; set; }
        public int price_id { get; set; }
        public bool deleted { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
