//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public string service_name { get; set; }
        public int service_price { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
